### ISSUE TITLE
turn tests into web services

### ISSUE THREAD

**Issue by menzowindhouwer** [CLARIAH/pyFAT#1]
https://github.com/CLARIAH/pyFAT/blob/develop/src/pyfat/resources/metrics/clarin_fip_metrics_v0.3.yaml defines a number of tests each identified by a `metric_test_identifier`, all these tests should become little web services:

1. make for each test a small yml file, e.g.`CLFIP-F1-01M-1`.yml
```yml

metric_test_identifier: CLFIP-F1-01M-1
metric_test_name: "Check to see if the selflink is a handle"
metric_test_score: 0.5
metric_test_requirements:
    - test: "xpath:starts-with(//cmd:MdSelfLink, 'hdl:')"
       modality: all
```
2. a flask server that creates an endpoint for each yml file, e.g. http://localhost/test/CLFIP-F1-01M-1
    1. it takes a POST of a CMDI record
    2. runs the test (see how https://github.com/CLARIAH/pyFAT/blob/develop/src/pyfat/__main__.py#L97 runs the test)
    3. return the result as JSON
----
max: 32 hours
hours can be written on `P:OSTrails`
@kerim1 can help
